### ISSUE TITLE
Выбор стека

### ISSUE THREAD

**Issue by alexbaumgertner** [AnnaApk/my-interviews#1]
Давай выберем стек. Я предлагаю NextJS 14 — хороший набор конфигураций и соглашений по умолчанию.
Можно деплоить на Vercel и другие хостинги бесплатно для пет-проектов.

По языку, можно JS, а можно и TS, зависит от того, что хочется изучить/развить.

Для базы данных можно MongoDB (есть бесплатные тарифы на MongoAtlas), но если есть желание — можно и что-нибудь из SQL.

Напиши в комментарии, на каком стеке тебе бы хотелось построить приложение?

**Comment by AnnaApk** [comment]
NextJS - хорошо.
Язык хотела бы TS, то же для меня новое будет, но сейчас как будто практически все вакансии с реактом идут в связке с TS.
По БД , хотела бы освоить SQL, не имела еще дела с такими. С mongo работала в процессе обучения на практикуме, и сама разобралась с farebase еще недавно на базовом уровне.

**Comment by AnnaApk** [comment]
Можно ли будет еще добавить в стэк state manager, например redux-toolkit?

**Comment by alexbaumgertner** [comment]
> Можно ли будет еще добавить в стэк state manager, например redux-toolkit?

Давай попробуем, там будут нюансы, но по крайней мере, есть пример от разработчиков nextjs
https://github.com/vercel/next.js/tree/canary/examples/with-redux

**Comment by alexbaumgertner** [comment]
Попробуй сделать PR с инициализацией NextJS
https://nextjs.org/docs/getting-started/installation#automatic-installation, давай использовать TypeScript, src directory, App Router, и алиасы.

**Comment by AnnaApk** [comment]
Создала проект, но для  nextJS требуется node от 18.17.0, у меня версия ниже. Почитала, кажется стоит установить nvm.
Но с ним какие-то проблемы, вот тут есть про отладку 
https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating 
буду завтра разбираться (он установился, папка появилась в директории, но в терминале пишет, что нет команды nvm).

**Comment by AnnaApk** [comment]
Создала проект , но оказалась нода на ноуте не той версии 16, что требуется для next от 18
Вчера попробовала установить nvm, он установился, но «из коробки» не заработал

прочитала что fnm еще аналогичный менеджер, а с ним проблема -висит на установке предпоследнего пакета 

Вот думаю, может переустановить систему и обновить, у меня мак, давно не обновляла

**Comment by AnnaApk** [comment]
создала проект!
обновила мак, установила fnm, теперь можно и проектом заниматься

обсуждения будут здесь все или под очередной этап - новое issue?

**Comment by alexbaumgertner** [comment]
Круто, что получилось поставить! На какой в итоге версии NodeJS получилось заработать?

**Comment by alexbaumgertner** [comment]
> обсуждения будут здесь все или под очередной этап - новое issue?

Новое issue.
https://github.com/AnnaApk/my-interviews/issues/2

**Comment by AnnaApk** [comment]
Поставила 20.10.0

**Comment by AnnaApk** [comment]
проект создала с tailwindcss, но вот думаю, что пока лучше без него и так много нового будет. 
Можно просто css? или лучше препроцессор?

**Comment by alexbaumgertner** [comment]
Я использую CSS modules, они уже в комплекте

**Comment by alexbaumgertner** [comment]
Тут думаю, мы все решили :)
