### ISSUE TITLE
Добавить API (бекенд на route-handlers)

### ISSUE THREAD

**Issue by alexbaumgertner** [AnnaApk/my-interviews#4]
https://nextjs.org/docs/app/building-your-application/routing/route-handlers

Можно сделать REST или GraphQL https://www.apollographql.com/docs/apollo-server/

Тебе какой интереснее?

**Comment by AnnaApk** [comment]
думаю, что пока буду разбираться с next-ом и его route-handlers

**Comment by alexbaumgertner** [comment]
Делаем REST, все ок :)
