### ISSUE TITLE
Добавить базу данных PostgreSQL

### ISSUE THREAD

**Issue by alexbaumgertner** [AnnaApk/my-interviews#5]
- [ ] выбрать PostgreSQL as a service, по типу Mongo Atlas (чтобы самим не устанавливать и настраивать) https://hasura.io/blog/top-postgresql-database-free-tier-solutions/
- [ ] выбрать ORM, можно и SQL builder (https://knexjs.org/guide/#typescript) — чтобы SQL подучить

**Comment by AnnaApk** [comment]
так как дела раньше не имела с sql, то для первого знакомства PostgreSQL

**Comment by AnnaApk** [comment]
если деплоить на vercel проект, то можно базой там же воспользоваться?

**Comment by alexbaumgertner** [comment]
> если деплоить на vercel проект, то можно базой там же воспользоваться?

Точно, там же есть https://vercel.com/docs/storage/vercel-postgres

Можно

**Comment by AnnaApk** [comment]
выполнив простые действия создала в проекте на версель PostgreSQL, теперь разбираюсь как с ней взаимодействовать

**Comment by AnnaApk** [comment]
написала добавление карточки в бд,
но пока больше вопросов

посмотри пожалуйста пул-реквест, писала чтобы просто хоть как-то работало и было на что писать замечания

правильно в принципе такое положение в структуре создания таблицы? потому что я сначало писала его и писала добавление после того как она создалась, и сейчас выходит что фетча по этому урлу нигде нет

**Comment by alexbaumgertner** [comment]
Вопросы — это хорошо! :)
Ты про этот ПР https://github.com/AnnaApk/my-interviews/pull/6 ?
Посмотрю сегодня вечером.

**Comment by AnnaApk** [comment]
Да, это он

**Comment by alexbaumgertner** [comment]
Посмотрел, добавил правки
https://github.com/AnnaApk/my-interviews/pull/6/commits/77ec93128d8491c3e675bb7321259d22fa1370ed

спрашивай, если что-то не понятно :)

**Comment by AnnaApk** [comment]
Первый вопрос!
Вообще если приложение публикуется/работает то правильно ли в принципе писать прям в нем создание таблицы? Не правильнее ли через терминал/вспомогательные приложения создавать ее на стадии разработки? А то выходит что постоянно будет вызываться функция проверки есть она или нет

**Comment by AnnaApk** [comment]
Ааа, миграция как раз про это 
Пошла читать

**Comment by AnnaApk** [comment]
Вопрос, при написании бэкенда нужно же пользоваться режимом разработки, и для него использовать свои переменные и сервер на localhost , а я сейчас выходит делаю все сразу в Версель. И там уже беспорядок, лишние таблицы.

**Comment by AnnaApk** [comment]
Про миграции, ими я могу удалить/откатить только то что через них создавалось ? И на каждое изменение будет создаваться свой файл миграции? То есть , в одном я создаю/удаляю таблицу, в другом переименовываю столбец, в третьем заменяю столбец на два других ?

**Comment by alexbaumgertner** [comment]
В миграциях можно делать произвольные изменения, но обычно первая миграция создает структуру в БД и получается, что дальнейшие миграции работают с созданной в предыдущих миграциях структурой.

Не помню кто изобрел такой подход, я познакомился с миграциями в https://guides.rubyonrails.org/active_record_migrations.html

**Comment by alexbaumgertner** [comment]
> И на каждое изменение будет создаваться свой файл миграции? То есть , в одном я создаю/удаляю таблицу, в другом переименовываю столбец, в третьем заменяю столбец на два других ?

Тут подход такой же, как с коммитами — одна миграция про какое-то атомарное законченное действие.

**Comment by AnnaApk** [comment]
добавила коммит - пересоздала таблицу через миграцию

сейчас без useStatе и с таким расположением логики карточки не обновляются при добавлении новой, переписать с  useStatе и вынести функцию добавления в page.tsx?

**Comment by alexbaumgertner** [comment]
> сейчас без useStatе и с таким расположением логики карточки не обновляются при добавлении новой, переписать с useStatе и вынести функцию добавления в page.tsx?

Да, из Form нужно вынести логику, попробуй сделать.
Посмотри еще на https://swr.vercel.app

PS: добавил коммит, исправляющий работу миграций.

**Comment by AnnaApk** [comment]
в этом коммите пока перенесла функцию в page из Form, без [swr ](https://swr.vercel.app)https://swr.vercel.app/ пока

**Comment by AnnaApk** [comment]
добавила swr для блока карточек, без кэша
