### ISSUE TITLE
Профиль пользователя 

### ISSUE THREAD

**Issue by alexbaumgertner** [AnnaApk/my-interviews#9]
- [ ] ФИО
- [ ] Опыт работы. Можно сделать сразу "период" - "компания" - "достижения" - "прокаченные скилы"
- [ ] Скиллы, которые есть и уровень владения
- [ ] Скиллы, которые хочу развить и уровень владения

**Comment by AnnaApk** [comment]
@alexbaumgertner 
Собрала первое приближение профиля #10 :
 - вынесу несколько компонентов, сейчас там все на главной странице
 - это только ui, по хранению данных:
 
таблица  users с пользователями (id, email, password)
таблица  users_experience (id, user_id, date_start, date_end, company, achiev, stack)
таблица  users_skills (user_id, skill_id, skill_required_level)
таблица  users_develop_skills (user_id, skill_id, skill_required_level)

 - так как на странице профиля тоже используется мульти выбор навыков и будет авторизация пользователей, вопрос - уже стоит добавить стэйт-менеджер, или на каждой странице "качать/следить" за данными?

**Comment by alexbaumgertner** [comment]
Спасибо!

Вместо паролей лучше использовать сторонние сервисы для входа, работа с паролями требует учета многих тонкостей по безопасности.
Есть выбор сервисов
https://nextjs.org/docs/pages/building-your-application/authentication#examples

**Comment by alexbaumgertner** [comment]
Я пробовал https://authjs.dev и видел https://clerk.com

**Comment by alexbaumgertner** [comment]
Закроем эту задачу?

Вынесу https://github.com/AnnaApk/my-interviews/pull/10#issuecomment-2112480653
> отобразить имя и написать запросы для записи/изменения остальных полей

в отдельную задачу https://github.com/AnnaApk/my-interviews/issues/12
